// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRcqXYWDKe5b5rcggvcHECW3285cu1H3Q',
    appId: '1:678590159867:web:6f2474ede639ebde7b095e',
    messagingSenderId: '678590159867',
    projectId: 'foodshare-e1ecb',
    authDomain: 'foodshare-e1ecb.firebaseapp.com',
    storageBucket: 'foodshare-e1ecb.firebasestorage.app',
    measurementId: 'G-XRNRQQ7PY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIjBhhyn2EAHGAWWoDUbsRAQCpvip_c6U',
    appId: '1:678590159867:android:45f0da0050f7fab87b095e',
    messagingSenderId: '678590159867',
    projectId: 'foodshare-e1ecb',
    storageBucket: 'foodshare-e1ecb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7U-JQih1wjGPOZ8djVtUtbvQbXtZjV0',
    appId: '1:678590159867:ios:66c4edee56654b247b095e',
    messagingSenderId: '678590159867',
    projectId: 'foodshare-e1ecb',
    storageBucket: 'foodshare-e1ecb.firebasestorage.app',
    iosBundleId: 'com.example.foodshare',
  );
}
